--- 
clone: 
  depth: 1
kind: pipeline
name: DaffaPipeline
steps: 
  - 
    commands:
      - "bash ./run.sh" 
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: compile
    trigger: 
      branch: 
        - master